//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adim
    {
        public int adimID { get; set; }
        public string adimAd { get; set; }
        public Nullable<bool> adimDurum { get; set; }
        public string adimNot { get; set; }
        public Nullable<System.DateTime> adimTarih { get; set; }
        public string adimFoto { get; set; }
        public string adimFotoAciklama { get; set; }
        public Nullable<int> turID { get; set; }
        public Nullable<int> yerID { get; set; }
    
        public virtual Tur Tur { get; set; }
        public virtual Yer Yer { get; set; }
    }
}
