//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltFirma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AltFirma()
        {
            this.Kotasyons = new HashSet<Kotasyon>();
        }
    
        public int altFirmaID { get; set; }
        public string altFirmaEmail { get; set; }
        public string altFirmaSifre { get; set; }
        public string altFirmaAd { get; set; }
        public string altFirmaTel { get; set; }
        public string altFirmaLogo { get; set; }
        public string altFirmaAdres { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kotasyon> Kotasyons { get; set; }
    }
}
