//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Kafile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kafile()
        {
            this.Turists = new HashSet<Turist>();
        }
    
        public int kafileID { get; set; }
        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string kafileAd { get; set; }
        [Required]
        public Nullable<int> kafileKisiSayisi { get; set; }
        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string kafileUlke { get; set; }
        public Nullable<int> turID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Tur Tur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turist> Turists { get; set; }
    }
}
