//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kotasyon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kotasyon()
        {
            this.AracKots = new HashSet<AracKot>();
            this.EkstraKots = new HashSet<EkstraKot>();
            this.MuzeKots = new HashSet<MuzeKot>();
            this.OtelKots = new HashSet<OtelKot>();
            this.ResKots = new HashSet<ResKot>();
        }
    
        public int kotasyonID { get; set; }
        public string kotasyonAd { get; set; }
        public Nullable<int> kotasyonGunSayisi { get; set; }
        public Nullable<System.DateTime> kotasyonBas { get; set; }
        public Nullable<System.DateTime> kotasyonBit { get; set; }
        public string kotasyonGelenUlke { get; set; }
        public string kotasyonGelenSehir { get; set; }
        public Nullable<int> kotasyonKisiSayisi { get; set; }
        public Nullable<double> kotasyonToplamTutar { get; set; }
        public Nullable<int> altFirmaID { get; set; }
        public Nullable<bool> onaylanmis { get; set; }
    
        public virtual AltFirma AltFirma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AracKot> AracKots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EkstraKot> EkstraKots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuzeKot> MuzeKots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtelKot> OtelKots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResKot> ResKots { get; set; }
    }
}
