//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourEntities : DbContext
    {
        public TourEntities()
            : base("name=TourEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AltFirma> AltFirmas { get; set; }
        public virtual DbSet<Arac> Aracs { get; set; }
        public virtual DbSet<AracKot> AracKots { get; set; }
        public virtual DbSet<Dil> Dils { get; set; }
        public virtual DbSet<Ekstra> Ekstras { get; set; }
        public virtual DbSet<EkstraKot> EkstraKots { get; set; }
        public virtual DbSet<Kotasyon> Kotasyons { get; set; }
        public virtual DbSet<Muze> Muzes { get; set; }
        public virtual DbSet<MuzeKot> MuzeKots { get; set; }
        public virtual DbSet<Otel> Otels { get; set; }
        public virtual DbSet<OtelKot> OtelKots { get; set; }
        public virtual DbSet<Rehber> Rehbers { get; set; }
        public virtual DbSet<ResKot> ResKots { get; set; }
        public virtual DbSet<Restorant> Restorants { get; set; }
        public virtual DbSet<Tur> Turs { get; set; }
        public virtual DbSet<TurArac> TurAracs { get; set; }
        public virtual DbSet<TurEkstra> TurEkstras { get; set; }
        public virtual DbSet<TurMuze> TurMuzes { get; set; }
        public virtual DbSet<TurOtel> TurOtels { get; set; }
        public virtual DbSet<TurRestorant> TurRestorants { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserTip> UserTips { get; set; }
        public virtual DbSet<Kafile> Kafiles { get; set; }
        public virtual DbSet<Turist> Turists { get; set; }
    }
}
