//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Otel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Otel()
        {
            this.OtelKots = new HashSet<OtelKot>();
            this.TurOtels = new HashSet<TurOtel>();
        }
    
        public int otelID { get; set; }
        public string otelAd { get; set; }
        public string otelTip { get; set; }
        public string otelTelefon { get; set; }
        public string otelAdres { get; set; }
        public string otelResim { get; set; }
        public Nullable<double> otelGecelikFiyat { get; set; }
        public string otelFiyatBirimi { get; set; }
        public Nullable<double> otelSingleRoomFiyat { get; set; }
        public Nullable<double> otelDoubleRoomFiyat { get; set; }
        public Nullable<double> otelKingSuitFiyat { get; set; }
        public Nullable<double> otelFamilyRoomFiyat { get; set; }
        public string otelLat { get; set; }
        public string otelLong { get; set; }
        public string otelIl { get; set; }
        public string otelIlce { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtelKot> OtelKots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurOtel> TurOtels { get; set; }
    }
}
