//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResKot
    {
        public int resKotID { get; set; }
        public string reskotTarih { get; set; }
        public Nullable<double> resToplamFiyat { get; set; }
        public Nullable<int> restorantID { get; set; }
        public int kotasyonID { get; set; }
    
        public virtual Kotasyon Kotasyon { get; set; }
        public virtual Restorant Restorant { get; set; }
    }
}
