//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restorant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restorant()
        {
            this.ResKots = new HashSet<ResKot>();
            this.TurRestorants = new HashSet<TurRestorant>();
        }
    
        public int restorantID { get; set; }
        public string restorantAd { get; set; }
        public string restorantAdres { get; set; }
        public string restorantIl { get; set; }
        public string restorantIlce { get; set; }
        public string restorantFoto { get; set; }
        public string restorantTelefon { get; set; }
        public Nullable<double> restorantKahvaltiFiyat { get; set; }
        public Nullable<double> restorantOglenFiyat { get; set; }
        public Nullable<double> restorantAksamFiyat { get; set; }
        public Nullable<double> restorantOrtalamFiyat { get; set; }
        public string restorantFiyatBirimi { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResKot> ResKots { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurRestorant> TurRestorants { get; set; }
    }
}
