//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tur()
        {
            this.TurAracs = new HashSet<TurArac>();
            this.TurEkstras = new HashSet<TurEkstra>();
            this.TurMuzes = new HashSet<TurMuze>();
            this.TurOtels = new HashSet<TurOtel>();
            this.TurRestorants = new HashSet<TurRestorant>();
            this.Kafiles = new HashSet<Kafile>();
        }
    
        public int turID { get; set; }
        public string turKod { get; set; }
        public string turAd { get; set; }
        public string turAciklama { get; set; }
        public Nullable<int> turGunSayisi { get; set; }
        public Nullable<System.DateTime> turBaslangic { get; set; }
        public Nullable<System.DateTime> turBitis { get; set; }
        public Nullable<int> turKisiSayisi { get; set; }
        public string turRenk { get; set; }
        public Nullable<bool> isFullDay { get; set; }
        public Nullable<bool> ertelenmis { get; set; }
        public Nullable<double> turToplamFiyat { get; set; }
        public Nullable<int> rehberID { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurArac> TurAracs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurEkstra> TurEkstras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurMuze> TurMuzes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurOtel> TurOtels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurRestorant> TurRestorants { get; set; }
        public virtual Rehber Rehber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kafile> Kafiles { get; set; }
    }
}
