//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurEkstra
    {
        public int turEkstraID { get; set; }
        public string turEkstraTarih { get; set; }
        public Nullable<double> turEkstraToplamFiyat { get; set; }
        public Nullable<int> ekstraID { get; set; }
        public Nullable<int> turID { get; set; }
    
        public virtual Ekstra Ekstra { get; set; }
        public virtual Tur Tur { get; set; }
    }
}
