//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Turist
    {
        public int turistID { get; set; }
        [StringLength(50, MinimumLength = 3)]
        public string turistAd { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Bu Alan Boþ Býrakýlamaz")]
        //[RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Lütfen Geçerli bir Telefon Numarasý Giriniz")]
        public string turistTel { get; set; }
        public string turistFoto { get; set; }
        public Nullable<short> turistYas { get; set; }
        public string turistCinsiyet { get; set; }
        //[RegularExpression(@"^\(?([1-9]{1}[0-9]{10})$", ErrorMessage = "Lütfen Geçerli bir TC Kimlik Numarasý Giriniz")]
        [Required(ErrorMessage = "Bu Alan Boþ Býrakýlamaz")]
        public string turistTC { get; set; }
        public string turistPasaportNo { get; set; }
        public string turistVizeNo { get; set; }
        public Nullable<int> kafileID { get; set; }
    
        public virtual Kafile Kafile { get; set; }
    }
}
