//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TurMuze
    {
        public int turMuzeID { get; set; }
        public string turMuzeTarih { get; set; }
        public Nullable<double> turMuzeToplamFiyat { get; set; }
        public Nullable<int> muzeID { get; set; }
        public Nullable<int> turID { get; set; }
    
        public virtual Muze Muze { get; set; }
        public virtual Tur Tur { get; set; }
    }
}
